### PR TITLE
Update ffnet node image

### PR DESCRIPTION
**Pull request by geigerzaehler**

### CODE REVIEW

**Comment by geigerzaehler** [comment]
Blocked by https://github.com/radicle-dev/radicle-registry/issues/493

**Comment by CodeSandwich** [comment]
I can't find the `421470d96225bd456acfd25289eeaedcc781d03d` tag on Google Cloud under `radicle-registry/node`, has the source of images changed?

**Comment by geigerzaehler** [comment]
I pushed this before it was build. It is here now: https://buildkite.com/monadic/radicle-registry/builds/2516#631bfbf7-d3b3-488f-aa88-59276a4d22e1

**Comment by CodeSandwich** [comment]
It's visible now :+1:

**Comment by geigerzaehler** [comment]
Blocked again by https://github.com/radicle-dev/radicle-registry/issues/505

**Pull request merged**
