### PR TITLE
Add docs for registry runtimes GCS

### PR DESCRIPTION
**Pull request by CodeSandwich**
Documents GCS for https://github.com/radicle-dev/radicle-registry/issues/492

### CODE REVIEW

**Comment by geigerzaehler** [comment]
Can we have this as a terraform file in `./registry`?

**Comment by CodeSandwich** [comment]
Since development of radicle registry is frozen, maybe we should merge it as it is now and create proper automation with terraform if we decide to continue?

**Comment by geigerzaehler** [comment]
Sounds good to me. Can you move the documentation to the `./registry` folder though? It is only concerned with registry infrastructure. A person that is only interested in the CI in general does not need to care for it.

**Comment by CodeSandwich** [comment]
I've moved all the docs for registry build artifacts from `CI/README.md` to `registry/README.md`

**Pull request merged**
